# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_10.addWidget(self.label_2, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.train_tab = QtWidgets.QWidget()
        self.train_tab.setObjectName("train_tab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.train_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.train_tab)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.train_algo_comboBox = QtWidgets.QComboBox(self.train_tab)
        self.train_algo_comboBox.setObjectName("train_algo_comboBox")
        self.train_algo_comboBox.addItem("")
        self.train_algo_comboBox.addItem("")
        self.train_algo_comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.train_algo_comboBox)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(self.train_tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.model_eval_imglabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.model_eval_imglabel.sizePolicy().hasHeightForWidth())
        self.model_eval_imglabel.setSizePolicy(sizePolicy)
        self.model_eval_imglabel.setObjectName("model_eval_imglabel")
        self.gridLayout.addWidget(self.model_eval_imglabel, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.train_tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.confusion_matrix_imglabel = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confusion_matrix_imglabel.sizePolicy().hasHeightForWidth())
        self.confusion_matrix_imglabel.setSizePolicy(sizePolicy)
        self.confusion_matrix_imglabel.setObjectName("confusion_matrix_imglabel")
        self.gridLayout_2.addWidget(self.confusion_matrix_imglabel, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.train_tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.fraction_incorrect_imglabel = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fraction_incorrect_imglabel.sizePolicy().hasHeightForWidth())
        self.fraction_incorrect_imglabel.setSizePolicy(sizePolicy)
        self.fraction_incorrect_imglabel.setObjectName("fraction_incorrect_imglabel")
        self.gridLayout_3.addWidget(self.fraction_incorrect_imglabel, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.train_tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_4.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.train_tab, "")
        self.prediction_tab = QtWidgets.QWidget()
        self.prediction_tab.setObjectName("prediction_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.prediction_tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.prediction_tab)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.prediction_algo_comboBox = QtWidgets.QComboBox(self.groupBox_5)
        self.prediction_algo_comboBox.setObjectName("prediction_algo_comboBox")
        self.prediction_algo_comboBox.addItem("")
        self.prediction_algo_comboBox.addItem("")
        self.prediction_algo_comboBox.addItem("")
        self.prediction_algo_comboBox.addItem("")
        self.verticalLayout.addWidget(self.prediction_algo_comboBox)
        self.browse_pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.browse_pushButton.setObjectName("browse_pushButton")
        self.verticalLayout.addWidget(self.browse_pushButton)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.prediction_tab)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.prediction_result_label = QtWidgets.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.prediction_result_label.setFont(font)
        self.prediction_result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.prediction_result_label.setObjectName("prediction_result_label")
        self.gridLayout_8.addWidget(self.prediction_result_label, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_8.addWidget(self.pushButton, 0, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_6)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_8.addWidget(self.line_4, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.prediction_tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.query_imglabel = QtWidgets.QLabel(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.query_imglabel.sizePolicy().hasHeightForWidth())
        self.query_imglabel.setSizePolicy(sizePolicy)
        self.query_imglabel.setObjectName("query_imglabel")
        self.gridLayout_6.addWidget(self.query_imglabel, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_7)
        self.gridLayout_9.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.prediction_tab, "")
        self.gridLayout_10.addWidget(self.tabWidget, 3, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_10.addWidget(self.line_2, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_10.addWidget(self.line_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "SKIN DISEASE CLASSIFICATION AND PREDICTION"))
        self.label.setText(_translate("MainWindow", "Select Algorithm"))
        self.train_algo_comboBox.setItemText(0, _translate("MainWindow", "DenseNet"))
        self.train_algo_comboBox.setItemText(1, _translate("MainWindow", "ResNet"))
        self.train_algo_comboBox.setItemText(2, _translate("MainWindow", "VGG"))
        self.groupBox.setTitle(_translate("MainWindow", "Model Evaluation"))
        self.model_eval_imglabel.setText(_translate("MainWindow", "img"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Confusion Matrix"))
        self.confusion_matrix_imglabel.setText(_translate("MainWindow", "img"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fraction classified incorrectly"))
        self.fraction_incorrect_imglabel.setText(_translate("MainWindow", "img"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Classification Report"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.train_tab), _translate("MainWindow", "Training Results"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Query"))
        self.prediction_algo_comboBox.setItemText(0, _translate("MainWindow", "Select Algorithm"))
        self.prediction_algo_comboBox.setItemText(1, _translate("MainWindow", "DenseNet"))
        self.prediction_algo_comboBox.setItemText(2, _translate("MainWindow", "ResNet"))
        self.prediction_algo_comboBox.setItemText(3, _translate("MainWindow", "VGG"))
        self.browse_pushButton.setText(_translate("MainWindow", "Browse Image"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Prediction"))
        self.prediction_result_label.setText(_translate("MainWindow", "Prediction Result"))
        self.pushButton.setText(_translate("MainWindow", "Start Prediction"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Query Image"))
        self.query_imglabel.setText(_translate("MainWindow", "img"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.prediction_tab), _translate("MainWindow", "Prediction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

